#!/usr/bin/env python3
"""Project the competitive-landscape data into a ranked "where we are worse" register.

Reads the CompetitiveLandscape source input, collects every `beats_us_on` finding (each a
place a competitor is stronger than the benchmark target), clusters findings by their
`capability` slug, and ranks the clusters by worst severity then by how many distinct
competitors share the gap. Emits a markdown register that states ONLY where we are behind —
by construction `our_position.distinctive_claims` never appear. This is the deliberately
one-sided view: it exists to find where we lose, not where we win.

Usage: python3 tools/generate_competitive_gap_register.py [--check]
  --check  exit non-zero if the committed register is stale vs. the data (CI gate).
"""
from __future__ import annotations

import collections
import sys
from pathlib import Path

try:
    import yaml
except Exception as exc:  # pragma: no cover
    raise SystemExit("pyyaml is required: `python -m pip install pyyaml`") from exc

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "source_inputs" / "competitive-intel" / "landscape.v0.yaml"
OUT = ROOT / "docs" / "competitive" / "where-we-stand.md"
SEV_WEIGHT = {"critical": 4, "high": 3, "medium": 2, "low": 1}


def render(doc: dict) -> str:
    comps = doc["spec"]["competitors"]
    by_cap: dict[str, list[dict]] = collections.defaultdict(list)
    by_cluster: collections.Counter = collections.Counter()
    for c in comps:
        by_cluster[c["cluster"]] += 1
        for g in c.get("beats_us_on", []):
            by_cap[g["capability"]].append(
                {"severity": g["severity"], "who": c["product"], "cluster": c["cluster"],
                 "evidence": g["evidence"], "source": g.get("source", "")})

    def rank_key(item):
        _, entries = item
        return (max(SEV_WEIGHT[e["severity"]] for e in entries), len(entries))

    ranked = sorted(by_cap.items(), key=rank_key, reverse=True)
    total_findings = sum(len(v) for v in by_cap.values())

    L = [
        "# Where We Stand — the honest gap register",
        "",
        f"> Generated by `tools/generate_competitive_gap_register.py` from "
        f"`{DATA.relative_to(ROOT).as_posix()}`. Do not hand-edit; edit the data and regenerate.",
        f"> Benchmark target: **{doc['metadata']['benchmark_target']}** — stage "
        f"`{doc['spec']['our_position']['maturity_stage']}`. Researched {doc['metadata']['researched_at']}.",
        ">",
        "> **This register lists ONLY where competitors are stronger than us.** It is one-sided by design.",
        "",
        f"**{len(comps)} products reviewed · {len(by_cap)} distinct capability gaps · "
        f"{total_findings} competitor-gap findings.**",
        "",
        "## Ranked gaps — most damaging first",
        "",
    ]
    for i, (cap, entries) in enumerate(ranked, 1):
        worst = max(entries, key=lambda e: SEV_WEIGHT[e["severity"]])["severity"]
        who = sorted({e["who"] for e in entries})
        L.append(f"### {i}. `{cap}` — **{worst}**, {len(entries)} competitors ahead")
        L.append(f"_ahead of us:_ {', '.join(who)}")
        L.append("")
        for e in sorted(entries, key=lambda e: -SEV_WEIGHT[e["severity"]]):
            src = f" ([src]({e['source']}))" if e["source"] else ""
            L.append(f"- **{e['who']}** ({e['severity']}): {e['evidence']}{src}")
        L.append("")

    L += ["## Findings by cluster", ""]
    for cluster, n in by_cluster.most_common():
        gaps = sum(len(g.get("beats_us_on", [])) for g in comps if g["cluster"] == cluster)
        L.append(f"- **{cluster}**: {n} products, {gaps} gap findings")
    L.append("")
    return "\n".join(L) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    doc = yaml.safe_load(DATA.read_text())
    rendered = render(doc)
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != rendered:
            print("STALE: where-we-stand.md is out of date — run generate_competitive_gap_register.py", file=sys.stderr)
            return 1
        print("ok: gap register is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
